# Generated by Django 5.2.6 on 2025-09-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_defaultaccounttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
