# Generated by Django 5.2.6 on 2025-10-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('association', 'voucher_type', 'voucher_number')},
        ),
    ]
